name: Reusable Deploy
on: 
  workflow_call: #Usado para especificar que será chamado por outro workflow
    inputs:
      artifact-name:  
        description: The name of the deployable artifacts files
        required: false
        type: string
        default: dist
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List  files
        run: ls
      - name: Output Information
        run: echo "Deployng and uploading..."